package soup.syntax.model;

import soup.syntax.model.declarations.Soup;
import soup.syntax.model.declarations.VariableDeclaration;
import soup.syntax.model.declarations.pieces.AnonymousPiece;
import soup.syntax.model.declarations.pieces.NamedPiece;
import soup.syntax.model.dependent.EnabledExpression;
import soup.syntax.model.dependent.InputReference;
import soup.syntax.model.dependent.NamedPieceReference;
import soup.syntax.model.dependent.PrimedReference;
import soup.syntax.model.expressions.ConditionalExpression;
import soup.syntax.model.expressions.Expression;
import soup.syntax.model.expressions.Reference;
import soup.syntax.model.expressions.binary.BinaryExpression;
import soup.syntax.model.expressions.binary.arithmetic.*;
import soup.syntax.model.expressions.binary.propositional.*;
import soup.syntax.model.expressions.binary.relational.*;
import soup.syntax.model.expressions.literals.BooleanLiteral;
import soup.syntax.model.expressions.literals.DoubleLiteral;
import soup.syntax.model.expressions.literals.IntegerLiteral;
import soup.syntax.model.expressions.literals.Literal;
import soup.syntax.model.expressions.unary.MinusExpression;
import soup.syntax.model.expressions.unary.NotExpression;
import soup.syntax.model.expressions.unary.PlusExpression;
import soup.syntax.model.expressions.unary.UnaryExpression;
import soup.syntax.model.statements.*;

public interface FunctionalVisitor<I, O> {
    O visit(SyntaxTreeElement node, I input);
    O visit(Expression node, I input);
    <X> O visit(Literal<X> node, I input);
    O visit(BooleanLiteral node, I input);
    O visit(IntegerLiteral node, I input);
    O visit(DoubleLiteral node, I input);
    <X> O visit(Reference<X> node, I input);
    O visit(UnaryExpression node, I input);
    O visit(NotExpression node, I input);
    O visit(PlusExpression node, I input);
    O visit(MinusExpression node, I input);
    O visit(BinaryExpression node, I input);
    O visit(Multiplication node, I input);
    O visit(Division node, I input);
    O visit(Modulus node, I input);
    O visit(Addition node, I input);
    O visit(Substraction node, I input);
    O visit(LessThan node, I input);
    O visit(LessThanOrEqual node, I input);
    O visit(GreaterThan node, I input);
    O visit(GreaterThanOrEqual node, I input);
    O visit(Equal node, I input);
    O visit(NotEqual node, I input);
    O visit(Conjunction node, I input);
    O visit(Disjunction node, I input);
    O visit(Implication node, I input);
    O visit(Equivalence node, I input);
    O visit(ExclusiveDisjunction node, I input);
    O visit(ConditionalExpression node, I input);
    O visit(Statement node, I input);
    O visit(Skip node, I input);
    O visit(Assignment node, I input);
    O visit(IfStatement node, I input);
    O visit(Sequence node, I input);
    O visit(AnonymousPiece node, I input);
    O visit(NamedPiece node, I input);
    O visit(VariableDeclaration node, I input);
    O visit(Soup node, I input);
    O visit(PrimedReference node, I input);
    O visit(NamedPieceReference node, I input);
    O visit(EnabledExpression node, I input);
    O visit(InputReference node, I input);
}
